- name: Install compat libs needed by mongo 3.2
  ansible.builtin.dnf:
    name:
      - compat-openssl10
    state: latest

- name: Create mongodb dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
    mode: '0755'
  loop:
    - { path: "{{ mongo36_path }}", owner: "{{ mongo36_user }}", group: "{{ mongo36_group }}" }
    - { path: "{{ mongo34_path }}", owner: "{{ mongo34_user }}", group: "{{ mongo34_group }}" }
    - { path: "{{ mongo32_path }}", owner: "{{ mongo32_user }}", group: "{{ mongo32_group }}" }

- name: Download and extract mongodb
  ansible.builtin.unarchive:
    extra_opts: [--strip-components=1]
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { src: "{{ mongo36_tgz }}", dest: "{{ mongo36_path }}", owner: "{{ mongo36_user }}", group: "{{ mongo36_group }}" }
    - { src: "{{ mongo34_tgz }}", dest: "{{ mongo34_path }}", owner: "{{ mongo34_user }}", group: "{{ mongo34_group }}" }
    - { src: "{{ mongo32_tgz }}", dest: "{{ mongo32_path }}", owner: "{{ mongo32_user }}", group: "{{ mongo32_group }}" }

- name: Generate config files
  template: 
    src: "{{ item }}.config.j2"
    dest: "/etc/{{ item }}.conf" 
    mode: 0644
  loop:
    - mongo36
    - mongo34
    - mongo32

- name: Set data dir permission
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: "{{ mongo36_data_path }}", owner: "{{ mongo36_user }}", group: "{{ mongo36_group }}" }
    - { path: "{{ mongo34_data_path }}", owner: "{{ mongo34_user }}", group: "{{ mongo34_group }}" }
    - { path: "{{ mongo32_data_path }}", owner: "{{ mongo32_user }}", group: "{{ mongo32_group }}" }